# -*- coding: utf-8 -*-
"""ChatBot AI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XXICCoqmlJw1qehZa7_n5_Mb8mvu-Y-E
"""

def chatbot_response(user_input):
    user_input = user_input.lower()  # Convert to lowercase for uniformity

    # Greetings
    if user_input in ["hello", "hi", "hey"]:
        return "Hello! How can I assist you today?"

    # Asking chatbot's name
    elif "your name" in user_input:
        return "I'm a simple chatbot created to assist you!"

    # Asking about time
    elif "time" in user_input:
        from datetime import datetime
        return f"The current time is {datetime.now().strftime('%H:%M:%S')}"

    # Asking about weather
    elif "weather" in user_input:
        return "I'm not connected to the internet, but you can check the weather on Google."

    # Goodbye
    elif user_input in ["bye", "goodbye"]:
        return "Goodbye! Have a great day! 😊"

    # Default response
    else:
        return "I'm sorry, I didn't understand that. Can you rephrase?"

while True:
    user_input = input("You: ")
    if user_input.lower() in ["exit", "quit", "bye"]:
        print("Chatbot: Goodbye! 👋")
        break
    response = chatbot_response(user_input)
    print("Chatbot:", response)

while True:
    user_input = input("You: ")
    if user_input.lower() in ["exit", "quit", "bye"]:
        print("Chatbot: Goodbye! 👋")
        break
    response = chatbot_response(user_input)
    print("Chatbot:", response)

import re

def chatbot_response(user_input):
    user_input = user_input.lower()

    if re.search(r"\b(hello|hi|hey)\b", user_input):
        return "Hello! How can I help you today?"

    elif re.search(r"\b(name)\b", user_input):
        return "I'm a chatbot created to chat with you!"

    elif re.search(r"\b(time)\b", user_input):
        from datetime import datetime
        return f"The current time is {datetime.now().strftime('%H:%M:%S')}"

    elif re.search(r"\b(weather)\b", user_input):
        return "I can't fetch the weather now, but you can check Google for live updates."

    elif re.search(r"\b(bye|goodbye|see you)\b", user_input):
        return "Goodbye! Have a nice day! 😊"

    else:
        return "I'm not sure how to respond to that. Could you ask differently?"

